[tox]
requires = tox-uv
envlist=
    lint
    py{310,311,312,313,314}
    py314-marshmallowdev
    py310-lowest
    docs

[testenv]
runner = uv-venv-lock-runner
extras = yaml,marshmallow
dependency_groups = tests
commands = pytest {posargs}

[testenv:py314-marshmallowdev]
runner = uv-venv-runner
deps = https://github.com/marshmallow-code/marshmallow/archive/dev.tar.gz

[testenv:py310-lowest]
runner = uv-venv-runner
deps = marshmallow==4.0.0

[testenv:lint]
dependency_groups = lint
skip_install = true
commands = pre-commit run --all-files

[testenv:docs]
extras = marshmallow
dependency_groups = docs
commands = sphinx-build docs/ docs/_build {posargs}

; Below tasks are for development only (not run in CI)

[testenv:docs-serve]
runner = uv-venv-runner
deps = sphinx-autobuild
extras = marshmallow
dependency_groups = docs
commands = sphinx-autobuild --port=0 --open-browser --delay=2 docs/ docs/_build {posargs} --watch src --watch README.rst

[testenv:readme-serve]
runner = uv-venv-runner
deps = restview
skip_install = true
commands = restview README.rst
